import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import {NextUIProvider} from "@nextui-org/react";
import { TRPCReactProvider } from "~/trpc/react";
import Navbarbar from "./_components/navbar";
import MySessionProvider from "./_components/MySessionProvider";
import { getServerAuthSession } from "~/server/auth";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <MySessionProvider session={session}>
              <Navbarbar />
              {children}
            </MySessionProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
