name: development

services:
  backend:
    container_name: backend
    image: guideai-backend:latest
    pull_policy: never
    env_file:
      - .env
    build:
      context: backend
      dockerfile: Dockerfile.dev
      cache_from:
        - guideai-backend:latest
      args:
        - DEV_MODE=true
    volumes:
      - ./backend/:/code/
    command:
      - "uvicorn"
      - "main:app"
      - "d"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5050"
      - "--workers"
      - "6"
      - "--log-level"
      - "info"
    restart: always
    ports:
      - 5050:5050
      - 5678:5678 # Debug PORT
