name: production

services:
  frontend:
    image: yyassif/guideai-frontend:latest
    container_name: web
    pull_policy: always
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    image: ghcr.io/yyassif/lguideai-backend:latest
    container_name: backend
    pull_policy: always
    restart: always
    env_file:
      - lguide.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5050/healthz"]
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5050"
      - "--workers"
      - "6"
    ports:
      - 5060:5050

networks:
  guideai:
    driver: bridge
