name: Build & Push Backend to Ghcr

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/backend-build-and-push.yml"

jobs:
  build_and_push:
    name: Build and Push Docker Image
    permissions: write-all
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker Cache Storage Backend
        run: |
          docker buildx create --use --driver=docker-container

      - name: See the file in the runner
        run: |
          ls -la

      - name: Build, Tag, and Push image to Ghcr.io.
        id: build-image
        uses: docker/build-push-action@v5
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          context: ./backend/
          push: true
          platforms: linux/amd64
          tags: ghcr.io/yyassif/lguideai-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
